TOPDIR = $(realpath ..)

SOURCES = \
	ctype/ctype.c \
	gen/divsi3.S \
	gen/modsi3.S \
	gen/mulsi3.S \
	gen/udivsi3.S \
	gen/umodsi3.S \
	stdio/kvprintf.c \
	stdlib/rand_r.c \
	stdlib/strtol.c \
	stdlib/strtoul.c \
	string/bzero.S \
	string/ffs.S \
	string/memcpy.S \
	string/memset.S \
	string/strcat.S \
	string/strchr.S \
	string/strcmp.S \
	string/strcpy.S \
	string/strcspn.c \
	string/strlen.S \
	string/strncmp.S \
	string/strncpy.S \
	string/strrchr.S \
	string/strspn.c \
	string/strtok_r.c

LIBNAME = c.lib

include $(TOPDIR)/build/build.lib.mk

# vim: ts=8 sw=8 noet
