TOPDIR = $(realpath ..)

SOURCES = amigahunk.c \
	  buf.c \
	  devfile.c \
	  file.c \
	  filedesc.c \
	  fs.c \
	  hexdump.c \
	  event.c \
	  intr.S \
	  intsrv.c \
	  memory.c \
	  msgport.c \
	  notify.c \
	  pipe.c \
	  port.c \
	  portasm.S \
	  printf.c \
	  proc.c \
	  ring.c \
	  sysent.c \
	  trapasm.S \
	  trap.c \
	  userent.S

LIBNAME = kernel.lib

include $(TOPDIR)/build/build.lib.mk

# vim: ts=8 sw=8 noet
