TOPDIR = $(realpath ..)

SOURCES = amigahunk.c \
	  buf.c \
	  device.c \
	  file.c \
	  filedesc.c \
	  hexdump.c \
	  intr.S \
	  intsrv.c \
	  kernio.c \
	  malloc.c \
	  pipe.c \
	  port.c \
	  portasm.S \
	  proc.c \
	  ring.c \
	  sysent.c \
	  trapasm.S \
	  trap.c \
	  tty.c \
	  userent.S

LIBNAME = kernel.lib

include $(TOPDIR)/build/build.lib.mk

# vim: ts=8 sw=8 noet
