TOPDIR = $(realpath ..)

SOURCES = \
	  cia-frame.c \
	  cia-icr.c \
	  cia-line.c \
	  cia-timer.c \
	  event.c \
	  floppy.c \
	  floppy-mfm.c \
	  keyboard.c \
	  mouse.c \
	  serial.c

LIBNAME = drivers.lib

include $(TOPDIR)/build/build.lib.mk

# vim: ts=8 sw=8 noet
