TOPDIR = $(realpath ..)

SOURCES = FreeRTOS_CLI.c
FORMAT-EXCLUDE = $(SOURCES) $(SOURCES_H)

LIBNAME = freertos-plus.lib

CPPFLAGS = -I$(TOPDIR)/FreeRTOS/include

include $(TOPDIR)/build/build.lib.mk

# vim: ts=8 sw=8 noet
